name: Deploy Supabase Function

on:
  push:
    branches:
      - main

jobs:
  deploy-supabase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Login to Supabase
      run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Set Supabase Secrets
      run: |
        supabase secrets set RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}
        supabase secrets set RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}

    - name: Deploy Supabase function
      run: supabase functions deploy create-razorpay-order
