name: Build, Deploy to Hostinger, and Update Supabase Secrets

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Vite project
      run: npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: public_html/

  update-supabase-secrets:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Set Supabase secrets
      run: |
        supabase secrets set RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}
        supabase secrets set RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}

    - name: Deploy Supabase function
      run: supabase functions deploy create-razorpay-order
